 uses "mcrypt.feh","string","console";
 
   string passphrase = "";
   string  password;
   string  encryptedPassword;
   string  decryptedPassword;
   password = String.escape(argv[0]);
   encryptedPassword = mCrypt.encryptMcryptography(password , passphrase);
   Console.println("encrypt:" + "${encryptedPassword}");
   decryptedPassword = mCrypt.decryptMcryptography(encryptedPassword , passphrase);
   Console.println("decrypt:" + "${decryptedPassword}");
  
   
